# services:
#   selenoid:
#     image: aerokube/selenoid:latest-release
#     container_name: selenoid
#     ports:
#       - "4444:4444"
#     volumes:
#       - "./browsers.json:/etc/selenoid/browsers.json"
#       - "/var/run/docker.sock:/var/run/docker.sock"
#     networks:
#       - selenoid
#     command: ["-conf", "/etc/selenoid/browsers.json", "-container-network", "selenoid"]

#   tests:
#     build: .
#     container_name: test_docker
#     depends_on:
#       selenoid:
#         condition: service_started
#     environment:
#       SELENOID_URL: "http://selenoid:4444/wd/hub"
#     volumes:
#       - ./allure-results:/app/allure-results
#     networks:
#       - selenoid
#     command: ["pytest", "-o", "testpaths=tests", "--alluredir=allure-results"]

# networks:
#   selenoid:
#     name: selenoid 

services:

  selenoid:
    image: "aerokube/selenoid"
    container_name: selenoid
    ports:
      - "4444:4444"
    networks:
      - selenoid
    volumes:
      - "./config.json:/etc/selenoid/config.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-conf", "/etc/selenoid/config.json", "-container-network", "selenoid"]

  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8081:8080"
    networks:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]

  test_docker:
    build: .
    container_name: test_docker
    links:
      - selenoid
    environment:
      - SELENOID_URL=http://selenoid:4444/wd/hub
    depends_on:
      - selenoid
    networks:
      - selenoid
    tty: true
    command: ["pytest"]

networks:
  selenoid:
    name: selenoid