name: Selenoid Tests Workflow
on:
  push:
    branches:
      - develop

jobs:
  run-selenoid-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Print project tree
        run: tree .
      
      - name: Pull selenoid image
        run: docker pull selenoid/chrome:128.0

      - name: Run tests in docker
        run: docker compose up --build --exit-code-from test_docker 
        env:
          SELENOID_URL: "http://selenoid:4444/wd/hub"

      - name: Save Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: ./allure-results