name: Selenoid Tests Workflow
on:
  push:
    branches:
      - develop

jobs:
  # Переименуем задачу
  run-selenoid-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Set up Docker Compose
        run: |
          docker compose up -d selenoid
          sleep 10  # Wait for Selenoid initialization
          
      - name: Run tests
        run: docker compose run tests

      - name: Save Allure results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: ./allure-results