name: Selenoid Tests Workflow
on:
  push:
    branches:
      - develop

jobs:
  run-selenoid-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Pull selenoid image
        run: docker pull selenoid/chrome:128.0

      - name: Run tests in docker
        run: docker compose up --build --exit-code-from test_docker 
        env:
          SELENOID_URL: "http://selenoid:4444/wd/hub"
        continue-on-error: true

      - name: Print project tree
        run: tree .
        
      # - name: Setup Java
      #   uses: actions/setup-java@v4
      #   with:
      #     java-version: 17
      #     distribution: 'temurin'
      
      # - name: Install Allure
      #   run: |
      #     wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
      #     tar -zxvf allure-2.27.0.tgz -C /opt/
      #     sudo ln -s /opt/allure-2.27.0/bin/allure /usr/bin/allure
      #     rm allure-2.27.0.tgz

      # - name: Generate Allure report
      #   run: allure generate allure-results -o allure-report --clean

      # - name: Save Allure report
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: allure-report
      #     path: ./allure-report

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        #id: allure-report
        with:
          allure_results: allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history